### ISSUE TITLE
"This project may contain sexually explicit content suited only for mature audiences"

### ISSUE THREAD

**Issue by blacklightpy** [Alex313031/atom-ng#12]
![image](https://github.com/Alex313031/atom-ng/assets/28739146/fac10255-b4a0-40d6-9a4b-710077334a6b)

**Comment by wravoc** [comment]
Same warning, very strange...

**Comment by blacklightpy** [comment]
@wravoc funny how https://github.com/stashapp/stash doesn't have it, yet a completely uninvolved text editor gets it.

**Comment by TheNotary** [comment]
M$'s way of telling us to give up and use vs code.

**Comment by KanuX-14** [comment]
It may have some leftovers? (https://github.com/Alex313031/atom-ng/commit/e428018f8077bdc7cfe71808e5e5cae047b59832)

**Comment by blacklightpy** [comment]
> It may have some leftovers? (https://github.com/Alex313031/atom-ng/commit/e428018f8077bdc7cfe71808e5e5cae047b59832)

Bruh
